### ISSUE TITLE
Readline visual glitch

### ISSUE THREAD

**Issue by manforowicz** [zyansheep/rustyline-async#18]
When reading input lines without printing anything between them, a text glitch occurs.

I noticed this while running `rustyline-async` version `0.4.0` in terminal on Linux. Code:

```rust
use rustyline_async::{Readline, ReadlineEvent};

#[tokio::main]
async fn main() {
    let (mut readline, _printer) = Readline::new("> ".to_string()).unwrap();
    
    while let ReadlineEvent::Line(text) = readline.readline().await.unwrap() {
        readline.add_history_entry(text.to_string());
    }
}
```
https://github.com/zyansheep/rustyline-async/assets/24969682/5ceccec4-57ca-4ee9-8a82-f119ffffcaa1

**Comment by zyansheep** [comment]
Merged, Thanks for the fix! Not sure how that didn't get caught... might have been a regression from a previous commit. I'll push a crates.io release when I get around to it :)
