### ISSUE TITLE
Shall `rustyline-async` depend on `noline` crate?

### ISSUE THREAD

**Issue by vi** [zyansheep/rustyline-async#2]
It seems like [`noline`](https://crates.io/crates/noline) is designed to be low-level part of other future line editors. Is it a good suite for `rustyline-async`?

**Comment by zyansheep** [comment]
It looks to me like `noline` is more of a competing package to `rustyline-async` then a low-level component. It seems to provide much of the same functionality (multiline editing, raw terminal mode, etc) with an easy interface like rustyline. Although as far as I can tell, it doesn't support simultaneous editing and printing like `rustyline-async` does. Currently this package uses `crossterm` as its backend.

If you want to accomplish something like https://github.com/rustne-kretser/noline/issues/10#issue-1222246744 It should be possible to do it with rustyline-async using ANSI codes to clear the screen. Although at that point, it might be a better idea to use a library purpose-built for making full screen console apps like [`cursive`](https://github.com/Gyscos/Cursive).

**Comment by eivindbergem** [comment]
`noline` is primarily targeted at `no_std` environments without dynamic allocation, and is fairy limited in terms of functionality because of this. It is not meant as a general purpose line editor backend.
