### ISSUE TITLE
Cannot clear prompt at end of program if there's nothing to write

### ISSUE THREAD

**Issue by jwodder** [zyansheep/rustyline-async#21]
As I understand it, the way to erase the readline prompt at the end of a program is to call `rl.flush()`; however, this only clears the prompt if there are lines written to the `SharedWriter` that have yet to be output.  If a program chooses to, say, just end immediately when the user enters "quit" without printing anything else, the prompt will be left behind on the screen, prepended to the user's shell prompt, which does not look good.

Possible ways to address this:

- Make `rl.flush()` always clear the input line even if no lines were output.
- Make `Readline` clear the input line on `Drop`
- Give `Readline` a public method for clearing the input line.

**Comment by zyansheep** [comment]
As a temporary fix, is it possible to print a newline before rl.flush() so that it looks nicer?

**Comment by jwodder** [comment]
@zyansheep You mean, just stick `writeln!(shared_writer)` before the call to `rf.flush()`?  That gets rid of the prompt, but then there's a superfluous blank line between the output and the shell prompt.

**Comment by zyansheep** [comment]
Hmm, this seems like an easy fix, but I'm not using this project atm (and probably won't spend much time maintaining / improving it) but if you want, I can give you commit access if you want to implement stuff yourself :)

**Comment by jwodder** [comment]
I appreciate the offer, but I'd rather stick to an "I create PR → You approve & merge" workflow, as I don't want to be unilaterally making any changes that might go against your wishes.  (Also, your involvement would still be needed to make crates.io releases.)

Here's a PR that takes approach number 1: #22.

**Comment by zyansheep** [comment]
> I'd rather stick to an "I create PR → You approve & merge" workflow, as I don't want to be unilaterally making any changes that might go against your wishes.

I don't mind people making changes that might go against my wishes... If I *really* don't like it, I will just revert the change :)

Mainly I'm suggesting this because I don't have the motivation to properly review PRs (pull, test for bugs, merge, push a new major version), and I've heard wonderful things about what happens when [you give away commit rights](https://www.youtube.com/watch?v=q4odN8N24qk), so I'm going to try and do that if I can :)

Do you think It'd be a good idea to move rustyline-async to a separate org?

**Comment by jwodder** [comment]
> Do you think It'd be a good idea to move rustyline-async to a separate org?

You can do that if you want, but personally I'd only recommend it if you planned to give multiple people (more than you & me) write permission.
