### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Siphalor** [zyansheep/rustyline-async#8]
Currently, this library has no explicit license, resulting in a strong copyright.

As you're welcoming contributions in the `README`, I suspect this to be an oversight.

You can check https://choosealicense.com/ for a simple overview over some free licenses.

Personally, I prefer using the MIT or Apache 2.0 licenses, but the final choice is up to you (and probably partially me because I contributed without noticing it and therefore probably have copyright on my stuff ^^ - but I'll go with any free license).

**Comment by zyansheep** [comment]
I defined the license in the Cargo.toml file
`license = "MIT OR Apache-2.0"`
But I suppose that is probably not standard, I shall make sure to pick a license through github.

**Comment by zyansheep** [comment]
Okay, I changed the license to the Unlicense License because [public domain is cool](https://www.youtube.com/watch?v=mnnYCJNhw7w).
