### ISSUE TITLE
Output to SharedWriter not shown when `break`ing after `writeln`

### ISSUE THREAD

**Issue by jwodder** [zyansheep/rustyline-async#9]
Environment:
* macOS 11.6.8
* Terminal.app (`TERM=xterm-256color`)
* Rust 1.65.0
* rustyline-async commit f9817e7 cloned from GitHub

When running the `readline` example in this repository, if I hit Ctrl-D, the program exits immediately without printing the "Exiting..." message, like so:

<img width="617" alt="Screen Shot 2022-11-19 at 15 37 18" src="https://user-images.githubusercontent.com/98207/202870753-b120af5d-f30e-4ecb-b121-70ac8ab8c152.png">

If I remove the `break` in the `Err(ReadlineError::Eof)` branch, the message is printed.

Similarly, if I add a `break` to the `Err(ReadlineError::Interrupted)` branch, pressing Ctrl-C results in the "^C" message not being printed — along with an additional prompt being printed before my shell command prompt, like so:

<img width="617" alt="Screen Shot 2022-11-19 at 15 41 39" src="https://user-images.githubusercontent.com/98207/202870881-9c1e15b2-ac75-4cfc-b433-d05a2dc9332f.png">

Adding `rl.flush()?;` or `Write::flush(&mut stdout)?;` after the call to `writeln` doesn't help.

Note that this isn't just limited to `Eof` and `Interrupted`, either.  When running the following code:

```rust
use rustyline_async::{Readline, ReadlineError};
use std::io::Write;
use std::time::Duration;
use tokio::time::sleep;

#[tokio::main]
async fn main() -> Result<(), ReadlineError> {
    let (mut rl, mut stdout) = Readline::new("> ".into())?;
    loop {
        tokio::select! {
            _ = sleep(Duration::from_secs(3)) => {
                writeln!(stdout, "Message received!")?;
            }
            cmd = rl.readline() => match cmd {
                Ok(line) => {
                    writeln!(stdout, "{line:?}")?;
                    rl.add_history_entry(line.clone());
                    if line == "quit" {
                        break;
                    }
                }
                Err(ReadlineError::Eof) => {
                    writeln!(stdout, "<EOF>")?;
                    break;
                }
                Err(ReadlineError::Interrupted) => {
                    writeln!(stdout, "<Ctrl-C>")?;
                    break;
                }
                Err(e) => {
                    writeln!(stdout, "Error: {e:?}")?;
                    break;
                }
            }
        }
    }
    Ok(())
}
```

typing "quit" will result in the program exiting without outputting `"quit"`, yet it still outputs the next readline prompt (which ends up prepended to my shell prompt), like so:

<img width="617" alt="Screen Shot 2022-11-19 at 16 12 05" src="https://user-images.githubusercontent.com/98207/202871784-2ae470ea-9ba4-40e9-b181-b65396934a2e.png">

**Comment by zyansheep** [comment]
Thanks for the report!

I think I made a bit of an oversight when designing because `Readline::readline()` deals with outputting to the terminal when polled in addition to reading from stdin. So if the readline is not polled (i.e. when you break from the loop) it doesn't handle the just written data.

The simplest fix is to just use `println!` instead of `writeln!` because stdout is not being handled anymore (and you are breaking out of the loop anyway)

A more concrete fix might be to change the `flush()` function so that it reads from the writers and writes to the terminals before flushing. This would require changing the output of `flush()` from `io::Result` to `Result<(), ReadlineError>`

Which would you prefer?

**Comment by jwodder** [comment]
@zyansheep I tried using `println!()` instead of `writeln!()` for outputting the "Exiting..." message, but that messed up my shell prompt even more:

<img width="617" alt="Screen Shot 2022-11-19 at 17 31 40" src="https://user-images.githubusercontent.com/98207/202874090-b57dc72d-d932-4e25-91ab-216308cfcf61.png">

I guess that leaves changing `flush()` as the only option.

**Comment by jwodder** [comment]
@zyansheep The PR works!  That was fast.  If you release this fix soon, you might want to also update the crossterm dependency version, as 0.25.0 is the latest now.

**Comment by zyansheep** [comment]
Done :tada:
